### PR TITLE
mount: Use "virtiofs" instead of "virtio_fs"

### PR DESCRIPTION
**Pull request by fidencio**
virtio_fs was the name used for the module in the very early stages of
its development.

Resolves: #232

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
I've just realized this one can be dropped as it depends on the patch done in the agent, which is just vendorized here.

Sorry for the noise and I'm closing this PR.

**Comment by fidencio** [comment]
I'm re-opening this one, just in order to add it as a dep of https://github.com/kata-containers/runtime/pull/2604

**Comment by chavafg** [comment]
@fidencio can you please rebase with latest changes to make travis happy?
Thanks

**Pull request merged**
