### PR TITLE
vendor: update agent dependency

### PR DESCRIPTION
**Pull request by bergwolf**
To include fixes for grpc encoder/decoder warnings.

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@bergwolf Did you `dep prune` ?

**Comment by bergwolf** [comment]
@sameo yes I did.

**Comment by jodh-intel** [comment]
Nits: It might be useful to add the following to the commit message:

- give an example of the encoder/decoder warnings this change fixes.
- identify which of the package(s) that have changed actually fixed those warnings.

lgtm

**Comment by bergwolf** [comment]
@jodh-intel the issue was reported here https://github.com/kata-containers/agent/issues/37
and as the title suggests, agent fixed the warnings. I've updated the commit message to include a sample of the warnings.

**Comment by jodh-intel** [comment]
Hi @bergwolf - thanks for providing the reference. I think that makes it much clearer and will us to perform any necessary "code archaeology" in the future. I've raised the suggestion that we start to use https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits on #kata-dev on Slack as it's easy to forget but really useful to have these references.

**Pull request merged**
