### PR TITLE
CI: Enable checkcommits

### LINKED ISSUE #16: Enable checkcommits
Enable static checks via https://github.com/kata-containers/tests/pull/7

### PR DESCRIPTION
**Pull request by jodh-intel**
Require all PRs to contain a "Fixes #XXX" comment and a
"Signed-off-by:" comment.

Fixes #16.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
See https://github.com/kata-containers/tests/pull/7.

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
Blocked on #31.

**Comment by jodh-intel** [comment]
Actually blocked on #32.

**Comment by laijs** [comment]
LGTM

**Pull request merged**
