### PR TITLE
vendor: Re-vendor agent and gRPC packages

### PR DESCRIPTION
**Pull request by jodh-intel**
Update the vendoring for the agent, and the dependent gRPC package. The
latter seems to currently be in a strange state since `Gopkg.toml` shows
it a `revision = "1.8.0", and yet that doesn't exist as a tag (although
`v1.8.0` *does*).

agent changes:

```
    0aae82b release: Kata Containers 1.4.0
    7b4c337 vendor: Update vendor/github.com/containerd/console
    8dedf30 agent: build as Position-Independent-Executable
    dc635d4 test: Add test for ipvlan routes in l3 mode
    69ee60f network: Refactor to reduce cyclomatic complexity
    4005c33 network: Handle default route where gateway is empty
    83138df pkg: types: Add a new field type
    a13144b proto: Split reusable structures into their own package
    3a678a9 agent: Fix the issue of stdout hang on builtin proxy
    d12910e agent: judge whether /sys/devices/system/memory/block_size_bytes exist.
    980023e agent: add support for guest-hooks
    e03f7d7 memory: Fix update memory path.
    a396a23 grpc: Add seccomp status to guest details
    7b71c10 grpc: Add agent details to guest details call
    4fefa1a release: Kata Containers 1.3.0
    a628496 device: rescan pci bus before waiting for new devices
    1310f3d device: fix redefined notify channel
    4163b8b uevent:Revert "device: check for existing device PCI path before waiting"
    54f77cf agent: support agent as init process in rootfs images
    ef62167 uevent: Add logs for uevents
    fc907f6 agent: fix the issue of missing close process terminal
    d71dd02 vendor: bump runtime-spec version
    28a5ab2 release: Kata Containers 1.3.0-rc1
    2b89a0a uevent: fix crash on read errors
    9cf56c0 agent: auto-online hotplug memory
    33aea09 CI: Add "make proto"
    00a5588 Makefile: Conditionally build agent with tag seccomp
    7e8e20b agent: add GetGuestDetails gRPC function
    7caf1c8 device: check for existing device PCI path before waiting
    3441244 device: do not close notify channel when wait timeout
    5936600 grpc: grpc.Code is deprecated
    2d3b9ac release: Kata Containers 1.3.0-rc0
    a6e27d6 client: fix dialer after vendor update
    cd03e0c vendor: update grpc-go dependency
    1d559a7 channel: add serial yamux channel close timeout
    fcf6fa7 agent: update resources list with the right device major-minor number
    8abc400 agent: add test to WaitProcess()
    f746ed8 agent: allow multiple waitProcess()
    157f1c1 travis: Add variable needed to run static checks
    ed54087 travis: bump golang version
    ba0c7fc client: wait for session to be fully closed
    0865c98 agent: wait session to be fully shutdown
    55f1480 vendor: update yamux dependency
    5e36bfc network: Wait for network device in UpdateInterface
    218ce89 device: Rename getBlockDeviceNodeName to getPCIDeviceName
    c9a4e2e uevent: Store the interface field as device name for network interfaces
    74a5364 build: fix make proto error
    b1c2ad8 agent: add support for online memory and cpu separately.
    6d26d61 client: Add context parameter and enable tracing support
    93fe84e protocols: increase dial timeout
    730b977 client: bypass grpc dialer backoff strategy
    41c09c2 agent: enable memory hierarchical account
    4f70b1c channel: remove unused functions
    f6486e7 channel: support communication channel hotplug
    28afabb release: Kata Containers 1.2.0
    7c287c6 agent: add ListInterfaces and ListRoutes rpc
    e398fd4 agent: add ReseedRandomDev rpc
    8a51909 codecov: remove codecov.yml
    745fa71 agent: set sandbox id log field in CreateSandbox
    a3321f4 vendor: Revendor netlink to fix PID 1 segfault
    a9ade15 agent: Add sandbox level reference counter for sandbox storage
    5f89c07 yamux: disable yamux keep alive in server channel
    815f831 agent: do not quit on grpc serve errors
    8abefd1 protocols/client: close yamux session when closing the stream
    67643cf agent: Fix CPU tests for both initrd and rootfs image
    cf8d3c8 agent: disable yamux keep alive
    ed656df grpc: Ignore WriteStdin after the standard input has been closed
    1a52204 grpc: Don't close the terminal on CloseStdin() call
    04457e3 logging: Add sandbox field
    ba2a32a create: Reduce cyclomatic complexity of CreateContainer
    bce5f78 logging: Redirect yamux warnings/errors to logger
    23311ea namespace: Add check to make sure PID namespace is not received
    7fe2eba release: Kata Containers 1.1.0
    4ef4971 travis: Enable travis ci for ppc64le
    57bf4e6 namespace: do not create path using rand.
    a589bdb CI: update static-checks.sh in travis.yml
    1372df2 logging: Fix handling of non-string fields when PID 1
    4018add agent: honour CPU constraints when agent is the init process
    1cff660 mount: Remove redundant mkdir
    cc74b5d network: Setup localhost when running as init
    dc06ec7 network: Add extra sanity checks
    b580ae7 network: Check all function parameters
    ee106e9 main: Exit(1) on error
    5bf3909 network: Reduce cyclomatic complexity
    cdf9bce namespace: Simplify code
    0d7f36f agent: update container cpuset cgroup parents
    4cf1809 agent: update container cpuset cgroup before setting the new configuration
    d70e5bb agent: don't modify container's config
    a30395a grpc: signal frozen containers
    08674c0 agent: Add support for ephemeral volumes
    c517125 ci: Refactor to pass metalinter checks
    ad9c33d tests: Modify tests to take into account if pid ns needs to be shared
    e334596 namespace: Share pid namespace of containers
    1e72fbb agent: Get cgroup mounts info from /proc/cgroups
    ab6c4ff namespaces: Create persistent UTS and IPC namespaces
    be3993e release: Kata Containers 1.0.0
    75c6fc0 grpc: implement pause and resume commands
    9da1fea release: Kata Containers 0.3.0
    4bad43e grpc: honour CPU constraints in Kubernetes
    11d5c56 grpc: log errors in async commands
    7b47559 channel: Support Epoll on Arm64
    a7033a7 release: update version to 0.2.0
    5c3c000 signal: Backtrace on SIGUSR1
    a0880aa signal: Switch to standard signal handling
    f8081ca main: Improve logging in signal handling loop
    075ad56 main: Rename signal functions for clarity
    899bc6d main: Log errors on failure
    6689db0 agent: Fix typo
    077e6f9 grpc : Add the StatsContainer api for `events cli`
    d29bf53 block: Get rid of device prediction for Storage as well
    3b565ad block: Use PCI address to determine block device name
    28cf91a grpc: implement update command
    d96b8e1 grpc: update cpuset cgroup
    d10734b uevent: Add a global listener for uevents
    4bcacdc network: Don't remove network routes or DNS when destroying sandbox
    1f5cf20 network: Don't store the network info as pointers if slices used
    185831c uevent: Capture device name in uevents
    8f828bb uevent: Fix netlink error while assigning pid in netlink client
    093f61b agent: add grpc tracer UT
    33bd601 agent: add server interceptor to log grpc requests
    ff7eaa1 grpc: add unit test for ListProcesses
    c394b63 mockcontainer: implement mockContainer
    d208929 mockreaper: add unit tests
    01bc953 grpc: implement ListProcesses
    134d5d5 test: add start/stop grpc server UT
    7e94246 agent: track grpc server
    9fb8024 UT: add tests for channel
    bea6183 agent: wait serial channel to be ready before reading
    f8c8c4c agent: accept grpc connections multiple times
    131554d network: specify netlink protocol
    49f01ed protocols/grpc: fix CPU hotplug race condition
    ee7850d mockreaper: implement mock reaper
    9f60034 reaper: implement reaper interface
    e37feac protocol: client: enable builtin yamux client support
    a862fea agent: Fix container creation rollback
    9602e11 vendor: Update libcontainer vendoring
    92f87a1 agent: Rollback properly when container creation fails
    128f87d mount: Correct error message with mount failure.
    7a182a4 device: VmPath can be empty if an Id is provided
    0275654 ci: lib: allow override of tests_repo
    205a4d7 github: Add issue template
    103aacd announce: Add total memory
    e277ec6 announce: Add device and storage handlers
    5d7463f announce: Add standard fields when running as PID 1
    4655950 agent: Add announce function
    5e6c385 CI: Require pullapprove ack for protocol changes
    5d40027 tests: Skip more tests if non-root
    4ba8499 tests: Use root skip function
    9a2da30 tests: Move helper function
    ae2be84 device: Add validation and debug
    9e7b27c mount: Log params and validate
    9760c10 device: Add SCSI block device support
    15e851f storage: Rework the way Storage and Device are handled
    4683745 lint: Remove unnecessary conversions
    058182d lint: Fix vet error
    ebcb3af reaper: removed unused type
    902b82c device: Use standard functions to get device Major and Minor
    6e262da main: Display full stacktrace on internal error
    5e7ea0f grpc: Handle hotplugged devices
    dce4ebd logging: Add source log field
    06ce859 All: change fmt.Errorf to grpcStatus
    0e58dd4 network: handle error case in getInterface/updateInterface
    3bfa071 CI: add setup.sh and run.sh to execute integration tests
    d41d4e3 grpc: network: remove Add/Update/Remove route support
    e16d5b1 network: add tests for updateRoutes
    614ad59 grpc: network: add UpdateRoutes
    4fc578f agent: Allow to retrieve the process of a stopped container
    bfcf5dd network: add initial tests
    cab528c grpc: initial changes for networking protocol
    27d9f2c agent: run init setup first
    8540821 agent: run init setup first
    17fdd1b log: disable color
    68794dd lint: Remove unused variables and struct fields
    acdb463 log: init logrus always before use it
    ae7887f vendor: prune unneeded code
    8a4d6e4 vendor: fix dep warning
    e51c454 doc: add CONTRIBUTING.md
    8fba14f agent: Fix the amount of bytes transmitted to the shim
    0aef782 CI: Run central go test script
    f3926bb build: add ppc64le support
    976ef0f agent: enable it to be the init process
    54afb09 client: Replace grpc.WithTimeout
    0d8ffbf CI: Require doc team signoff for doc changes
    ee518f8 grpc: Fix not online Mem
    9ed615c CI: switch to central static check script
    cac185a CI: Rename static check script
    045c2cf grpc: Split execProcess in more readable functions
    71dd0b8 protocols: grpc: Fix the spec converter regarding nil pointers
    532325c grpc: Move sequencing from StartContainer to CreateContainer
    5ebcaec CI: Fix gometalinter errors
    fb52144 vendor: Update testify for latest assert
    3dd881f grpc: Reference appropriate process when starting a container
    b2f30e1 grpc: Lock the container creation
    92a2a6a grpc: Remove unused code parts
    d3a27ca agent: Add missing nsenter import
    4f73ac9 mount: Create destination directory for 9pfs as well
    1327404 mount: Do not shadow absSource
    0759700 grpc: Return nil from SignalProcess() if container already stopped
    9d6298b vendor: Re-vendor libcontainer for SIGKILL fix
    3d44912 agent: allow exec before start
    35e36c6 test: Increase unit test coverage
    d1fd1f3 agent: Close appropriate file handler
    8322c0c codecov: Add codecov.yml
```

gRPC changes:

```
    d11072e Change version to 1.11.3
    d06e756 clientconn: add support for unix network in DialContext. (#1883)
    452c2a7 Change version to 1.11.3-dev
    d89cded Change version to 1.11.2
    98ac976 server: add grpc.Method function for extracting method from context (#1961)
    0f5fa28 Change version to 1.11.2-dev
    1e2570b Change version to 1.11.1
    d28faca client: Fix race when using both client-side default CallOptions and per-call CallOptions (#1948)
    48b7669 Change version to 1.11.1-dev
    afc05b9 Change version to 1.11.0
    f2620c3 resolver: keep full unparsed target string if scheme in parsed target is not registered (#1943)
    9d2250f status: rename Status to GRPCStatus to avoid name conflicts (#1944)
    2756956 status: Allow external packages to produce status-compatible errors (#1927)
    0ff1b76 routeguide: reimplement distance calculation
    dfbefc6 service reflection can lookup enum, enum val, oneof, and field symbols (#1910)
    32d9ffa Documentation: Fix broken link in rpc-errors.md (#1935)
    d5126f9 Correct Go 1.6 support policy (#1934)
    5415d18 Add documentation and example of adding details to errors (#1915)
    57640c0 Allow storing alternate transport.ServerStream implementations in context (#1904)
    031ee13 Fix Test: Update the deadline since small deadlines are prone to flakes on Travis. (#1932)
    2249df6 gzip: Add ability to set compression level (#1891)
    8124abf credentials/alts: Remove the enable_untrusted_alts flag (#1931)
    b96718f metadata: Fix bug where AppendToOutgoingContext could modify another context's metadata (#1930)
    738eb6b fix minor typos and remove grpc.Codec related code in TestInterceptorCanAccessCallOptions (#1929)
    211a7b7 credentials/alts: Update ALTS "New" APIs (#1921)
    fa28bef client: export types implementing CallOptions for access by interceptors (#1902)
    ec9275b travis: add Go 1.10 and run vet there instead of 1.9 (#1913)
    13975c0 stream: split per-attempt data from clientStream (#1900)
    2c2d834 stats: add BeginTime to stats.End (#1907)
    3a9e1ba Reset ping strike counter right before sending out data. (#1905)
    90dca43 resolver: always fall back to default resolver when target does not follow URI scheme (#1889)
    9aba044 server: Convert all non-status errors to codes.Unknown (#1881)
    efcc755 credentials/alts: change ALTS protos to match the golden version (#1908)
    0843fd0 credentials/alts: fix infinite recursion bug [in custom error type] (#1906)
    207e276 Fix test race: Atomically access minConnecTimout in testing environment. (#1897)
    3ae2a61 interop: Add use_alts flag to client and server binaries (#1896)
    5190b06 ALTS: Simplify "New" APIs (#1895)
    7c5299d Fix flaky test: TestCloseConnectionWhenServerPrefaceNotReceived (#1870)
    f0a1202 examples: Replace context.Background with context.WithTimeout (#1877)
    a1de3b2 alts: Change ALTS proto package name (#1886)
    2e7e633 Add ALTS code (#1865)
    583a630 Expunge error codes that shouldn't be returned from library (#1875)
    2759199 Small spelling fixes (unknow -> unknown) (#1868)
    12da026 clientconn: fix a typo in GetMethodConfig documentation (#1867)
    dfa1834 Change version to 1.11.0-dev (#1863)
    46fd263 benchmarks: add flag to benchmain to use bufconn instead of network (#1837)
    3926816 addrConn: Report underlying connection error in RPC error (#1855)
    445b728 Fix data race in TestServerGoAwayPendingRPC (#1862)
    e014063 addrConn: keep retrying even on non-temporary errors (#1856)
    484b3eb transport: fix race causing flow control discrepancy when sending messages over server limit (#1859)
    6c48c7f interop test: Expect io.EOF from stream.Send() (#1858)
    08d6261 metadata: provide AppendToOutgoingContext interface (#1794)
    d50734d Add status.Convert convenience function (#1848)
    365770f streams: Stop cleaning up after orphaned streams (#1854)
    7646b53 transport: support stats.Handler in serverHandlerTransport (#1840)
    104054a Fix connection drain error message (#1844)
    d09ec43 Implement unary functionality using streams (#1835)
    37346e3 Revert "Add WithResolverUserOptions for custom resolver build options" (#1839)
    424e3e9 Stream: do not cancel ctx created with service config timeout (#1838)
    f9628db Fix lint error and typo (#1843)
    0bd008f stats: Fix bug causing trailers-only responses to be reported as headers (#1817)
    5769e02 transport: remove unnecessary rstReceived (#1834)
    0848a09 transport: remove redundant check of stream state in Write (#1833)
    c22018a client: send RST_STREAM on client-side errors to prevent server from blocking (#1823)
    82e9f61 Use keyed fields for struct initializers (#1829)
    5ba054b encoding: Introduce new method for registering and choosing codecs (#1813)
    4f7a2c7 compare atomic and mutex performance in case of contention. (#1788)
    b71aced transport: Fix a data race when headers are received while the stream is being closed (#1814)
    46bef23 Write should fail when the stream was done but context wasn't cancelled. (#1792)
    10598f3 Explain target format in DialContext's documentation (#1785)
    08b7bd3 gzip: add Name const to avoid typos in usage (#1804)
    8b02d69 remove .please-update (#1800)
    1cd2346 Documentation: update broken wire.html link in metadata package. (#1791)
    6913ad5 Document that all errors from RPCs are status errors (#1782)
    8a8ac82 update const order (#1770)
    e975017 Don't set reconnect parameters when the server has already responded. (#1779)
    7aea499 credentials: return Unavailable instead of Internal for per-RPC creds errors (#1776)
    c998149 Avoid copying headers/trailers in unary RPCs unless requested by CallOptions (#1775)
    8246210 Update version to 1.10.0-dev (#1777)
    17c6e90 compare atomic and mutex performance for incrementing/storing one variable (#1757)
    65c901e Fix flakey test. (#1771)
    7f2472b grpclb: Remove duplicate init() (#1764)
    09fc336 server: fix bug preventing Serve from exiting when Listener is closed (#1765)
    035eb47 Fix TestGracefulStop flakiness (#1767)
    2720857 server: fix race between GracefulStop and new incoming connections (#1745)
    0547980 Notify parent ClientConn to re-resolve in grpclb (#1699)
    e6549e6 Add dial option to set balancer (#1697)
    6610f9a Fix test: Data race while resetting global var. (#1748)
    f4b5237 status: add Code convenience function (#1754)
    47bddd7 vet: run golint on _string files (#1749)
    45088c2 examples: fix concurrent map accesses in route_guide server (#1752)
    4e393e0 grpc: fix deprecation comments to conform to standard (#1691)
    0b24825 Adjust keepalive paramenters in the test such that scheduling delays don't cause false failures too often. (#1730)
    f9390a7 fix typo (#1746)
    6ef45d3 fix stats flaky test (#1740)
    98b17f2 relocate check for shutdown in ac.tearDown() (#1723)
    5ff10c3 fix flaky TestPickfirstOneAddressRemoval (#1731)
    2625f03 bufconn: allow readers to receive data after writers close (#1739)
    b0e0950 After sending second goaway close conn if idle. (#1736)
    b8cf13e Make sure all goroutines have ended before restoring global vars. (#1732)
    4742c42 client: fix race between server response and stream context cancellation (#1729)
    8fba5fc In gracefull stop close server transport only after flushing status of the last stream. (#1734)
    d1fc8fa Deflake tests that rely on Stop() then Dial() not reconnecting (#1728)
    dba60db Switch balancer to grpclb when at least one address is grpclb address (#1692)
    ca1b23b Update CONTRIBUTING.md to CNCF CLA
    2941ee1 codes: Add UnmarshalJSON support to Code type (#1720)
    ec61302 naming: Fix build constraints for go1.6 and go1.7 (#1718)
    b8191e5 remove stringer and go generate (#1715)
    ff1be3f Add WithResolverUserOptions for custom resolver build options (#1711)
    580defa Fix grpc basics link in route_guide example (#1713)
    b7dc71e Optimize codes.String() method using a switch instead of a slice of indexes (#1712)
    1fc873d Disable ccBalancerWrapper when it is closed (#1698)
    bf35f1b Refactor roundrobin to support custom picker (#1707)
    4308342 Change parseTimeout to not handle non-second durations (#1706)
    be07790 make load balancing policy name string case-insensitive (#1708)
    cd563b8 protoCodec: avoid buffer allocations if proto.Marshaler/Unmarshaler (#1689)
    61c6740 Add comments to ClientConn/SubConn interfaces to indicate new methods may be added (#1680)
    ddbb27e client: backoff before reconnecting if an HTTP2 server preface was not received (#1648)
    a4bf341 use the request context with net/http handler (#1696)
    c6b4608 transport: fix race sending RPC status that could lead to a panic (#1687)
    00383af Fix misleading default resolver scheme comments (#1703)
    a62701e Eliminate data race in ccBalancerWrapper (#1688)
    1e1a47f Re-resolve target when one connection becomes TransientFailure (#1679)
    2ef021f New grpclb implementation (#1558)
    10873b3 Fix panics on balancer and resolver updates (#1684)
    646f701 Change version to 1.9.0-dev (#1682)
```

Includes minimal changes for:

- New agent `NewAgentClient()` API arguments.
- Static analysis fixes:
  ```
  pipe.go:58:5warning grpc.Code is deprecated: use status.FromError and Code method instead.  (SA1019) (staticcheck)
  pipe.go:58:43warning grpc.ErrorDesc is deprecated: use status.FromError and Message method instead.  (SA1019) (staticcheck)
  ```

Fixes: #123, fixes: #126.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Wow, we've been busy on the agent :smile:

This is needed for #123.

**Comment by devimc** [comment]
CI is not happy

```
/home/travis/gopath/src/github.com/kata-containers/shim
pipe.go:58:5:warning: grpc.Code is deprecated: use status.FromError and Code method instead.  (SA1019) (staticcheck)
pipe.go:58:43:warning: grpc.ErrorDesc is deprecated: use status.FromError and Message method instead.  (SA1019) (staticcheck)
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by jodh-intel** [comment]
Branch updated.

**Comment by jodh-intel** [comment]
Umm, branch *updating* in fact...

**Comment by jodh-intel** [comment]
Finally, branch updated!

**Comment by caoruidong** [comment]
BTW, will we switch to vgo someday?

**Comment by jodh-intel** [comment]
@caoruidong - why don't you raise a https://github.com/kata-containers/kata-containers/issues/new to discuss it and add it to the Arch Committee agenda?

**Comment by jodh-intel** [comment]
Ping @jodh-intel - any update on this?

Hi @jodh-intel - why yes - all CI tests have passed. I'm just waiting for acks from @kata-containers/shim :smile:

**Comment by caoruidong** [comment]
lgtm

**Comment by caoruidong** [comment]
@jodh-intel just curios, I think vgo is still [experimental]. I will keep that in my mind :smiley:

**Comment by devimc** [comment]
lgtm

**Pull request merged**
