### PR TITLE
 Docs : Add minimal contribution guidelines

### PR DESCRIPTION
**Pull request by ydjainopensource**
Fixes : #40

See : kata-containers/community#5

Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks again @ydjainopensource - this is really helpful :smile:

lgtm

@klynnrif, @rcaballeromx - and another small one.

[Approved with PullApprove](https://pullapprove.com/kata-containers/shim/pull-request/41/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=kata-containers/shim) [Approved with PullApprove](https://pullapprove.com/kata-containers/shim/pull-request/41/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=kata-containers/shim)

**Comment by ydjainopensource** [comment]
@jodh-intel Wow that was fast. I didn't expect a reply this soon.

Travis is still failing I tried changing the ordering. Now it won't recognize the fixes tag.

**Comment by jodh-intel** [comment]
Hi @ydjainopensource - I've checked and the problem is that `checkcommits` doesn't like the space between "`Fixes`" and "`:`". So, you could change that line to either:

```
Fixes #40
```

Or

```
Fixes: #40
```

If you want to raise a bug on `checkcommits` at the URL below [1], I'll take a look:

- https://github.com/kata-containers/tests/issues/new

---
[1] - The tool lives here: https://github.com/kata-containers/tests/tree/master/cmd/checkcommits

**Comment by jodh-intel** [comment]
Hi @kata-containers/shim - we need 1 more ack for this 5-line doc fix.

**Comment by jodh-intel** [comment]
Hi @ydjainopensource  - please could you change the `Fixes` line to make it either `Fixes: #40` or `Fixes #40` to keep `checkcommits` happy :)

**Comment by ydjainopensource** [comment]
I have changed the fixes lines. hopefully it should work now

**Comment by jodh-intel** [comment]
Thanks @ydjainopensource - yes, Travis is now happy. We just need one more ack.

**Comment by sameo** [comment]
LGTM

**Pull request merged**
