### PR TITLE
lint: linter issue fixes

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Fixes: #164

Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

### CODE REVIEW

**Comment by teawater** [comment]
@ganeshmaharaj you need update dist to xenial to handle travis fail like https://github.com/kata-containers/agent/pull/528

**Comment by ganeshmaharaj** [comment]
@teawater thanks for the tip. Updated the branch with the travis fix for distro.

**Comment by ganeshmaharaj** [comment]
@teawater seems like even with the travis change to move to xenial we are hitting the issue. is there something else that i am missing here?

**Comment by teawater** [comment]
> @teawater seems like even with the travis change to move to xenial we are hitting the issue. is there something else that i am missing here?

I doesn't have any idea on this issue.  It looks like a new issue. :(
Report it to travis in https://support.travis-ci.com/hc/en-us/requests/6263

**Comment by grahamwhaley** [comment]
Before we go issuing reports to Travis (as, lets be honest, the last one we issued was not their fault - it was a go issue that showed up due to our travis config file being out of date....).... let's see if we can figure out what the problem actually is. 9 times out of 10 I think it will not be Travis itself...

It's odd, looking at the Travis status/log, I see 4 travis builds for that PR - Linux, OSX, ppc64 Linux .... and then another Linux. I don't understand why we have two Linux ones there (I don't think I see two in the config file). Of the two Linux builds, one passed and one failed.

Looking at the changes, and the fact that we have a Linux travis pass, this all lgtm.
@chavafg - can you give it a look over for me?

**Comment by chavafg** [comment]
took a look and it is indeed weird, two linux (amd64) jobs and one fails and the other passes...

**Comment by ganeshmaharaj** [comment]
@grahamwhaley @jcvenegas could the duplicate be because of us specifying linux twice. https://github.com/kata-containers/shim/blob/1a87aba3bfeea9fe2022a375aa2807ef2def03e2/.travis.yml#L9-L14 Once in the matrix and second in the os section?

**Comment by grahamwhaley** [comment]
Thanks @ganeshmaharaj - yeah, looking at the runtime repo config for instance, I'm not sure we use matrix anywhere else. Maybe check the `git blame` to find out where and why it was introduced, just in case?

**Comment by ganeshmaharaj** [comment]
@grahamwhaley seems it all landed at the same time to get darwin enabled via 27339b0590243067af7dac7412e0e863513c3c51 will submit a PR to clean it out.

**Comment by ganeshmaharaj** [comment]
Seems these are the reasons for the failures.
`jenkins-ci-Power8-ubuntu-16-04-initrd`

```
+ git clone https://github.com/kata-containers/tests.git /home/jenkins/workspace/kata-containers-shim-Power8-ubuntu-16-04-PR-initrd/go/src/github.com/kata-containers/tests
fatal: destination path '/home/jenkins/workspace/kata-containers-shim-Power8-ubuntu-16-04-PR-initrd/go/src/github.com/kata-containers/tests' already exists and is not an empty directory.
Build step 'Execute shell' marked build as failure
Performing Post build task...
```

`jenkins-ci-centos-7-4-q-35`

```
• Failure [30.404 seconds]
[Serial Test] Update number of CPUs
/tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:228
  Update CPU constraint
  /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    should have 2 CPUs [It]
    /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected
        <int>: 1
    to be zero-valued

    /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:299
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [Serial Test] Update number of CPUs Update CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:299
```
Not sure this patch should affect that error.

`jenkins-ci-ubuntu-nemu`

```
13:22:21 • Failure in Spec Teardown (AfterEach) [10.502 seconds]
13:22:21 [k8s.io] Container
13:22:21 /tmp/jenkins/workspace/kata-containers-shim-ubuntu-nemu/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
13:22:21   runtime should support basic operations on container
13:22:21   /tmp/jenkins/workspace/kata-containers-shim-ubuntu-nemu/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:68
13:22:21     runtime should support creating container [Conformance] [AfterEach]
13:22:21     /tmp/jenkins/workspace/kata-containers-shim-ubuntu-nemu/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:83
13:22:21 
13:22:21     failed to pull image: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:1.28": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:432b65032b9466b4dadcc5c7b11701e71d21c18400aae946b101ad16be62333a: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount558178608: link /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/[ /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/softlimit: no such file or directory: unknown
13:22:21     Expected error:
13:22:21         <*status.statusError | 0xc0005c2240>: {
13:22:21             Code: 2,
13:22:21             Message: "failed to pull and unpack image \"docker.io/library/busybox:1.28\": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:432b65032b9466b4dadcc5c7b11701e71d21c18400aae946b101ad16be62333a: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount558178608: link /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/[ /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/softlimit: no such file or directory: unknown",
13:22:21             Details: nil,
13:22:21         }
13:22:21         rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:1.28": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:432b65032b9466b4dadcc5c7b11701e71d21c18400aae946b101ad16be62333a: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount558178608: link /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/[ /var/lib/containerd/tmpmounts/containerd-mount558178608/bin/softlimit: no such file or directory: unknown
13:22:21     not to have occurred
```

@jcvenegas @chavafg

**Comment by chavafg** [comment]
@ganeshmaharaj I still see travis failing. we can disregard the others.

**Comment by jcvenegas** [comment]
centos failed not related error 
```
• Failure [30.404 seconds]
[Serial Test] Update number of CPUs
/tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:228
  Update CPU constraint
  /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    should have 2 CPUs [It]
    /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected
        <int>: 1
    to be zero-valued

    /tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:299
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [Serial Test] Update number of CPUs Update CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-shim-centos-7-4-q-35-PR/go/src/github.com/kata-containers/tes
```

**Comment by jcvenegas** [comment]
power8:
Non related issue gcc+go build failed probably non updated gcc 
```
INFO: Running 'go test' as current user on package 'github.com/kata-containers/shim' with flags '-v -race -timeout 30s -outputdir "/tmp/tmp.7jHsIbd5Qp"'
# github.com/kata-containers/shim.test
/home/travis/.gimme/versions/go1.11.8.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-289055635/000006.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by jodh-intel** [comment]
Hmm, the CentOS CI job isn't being retriggered...?!?

**Comment by jodh-intel** [comment]
Metrics CI suffering from Java borkage (restarted):

```
14:46:49  > git checkout -f 06956d22fa07f0b5366497ca7a5518a661938010 # timeout=10
14:46:56 FATAL: java.io.IOException: Unexpected termination of the channel
14:46:56 java.io.EOFException
14:46:56 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
14:46:56 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
14:46:56 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
14:46:56 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
14:46:56 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
14:46:56 	at hudson.remoting.Command.readFrom(Command.java:140)
14:46:56 	at hudson.remoting.Command.readFrom(Command.java:126)
14:46:56 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
14:46:56 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
14:46:56 Caused: java.io.IOException: Unexpected termination of the channel
14:46:56 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
14:46:56 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to x86_packet02
14:46:56 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
14:46:56 		at hudson.remoting.Request.call(Request.java:202)
14:46:56 		at hudson.remoting.Channel.call(Channel.java:956)
14:46:56 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
14:46:56 		at com.sun.proxy.$Proxy391.withRepository(Unknown Source)
14:46:56 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:237)
14:46:56 		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1263)
14:46:56 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1236)
14:46:56 		at hudson.scm.SCM.checkout(SCM.java:504)
14:46:56 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
14:46:56 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
14:46:56 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
14:46:56 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
14:46:56 		at hudson.model.Run.execute(Run.java:1816)
14:46:56 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:46:56 		at hudson.model.ResourceController.execute(ResourceController.java:97)
14:46:56 		at hudson.model.Executor.run(Executor.java:429)
14:46:56 Caused: hudson.remoting.RequestAbortedException
14:46:56 	at hudson.remoting.Request.abort(Request.java:340)
14:46:56 	at hudson.remoting.Channel.terminate(Channel.java:1040)
14:46:56 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:94)
```

**Comment by grahamwhaley** [comment]
The JAVA stack dumps we see from the CI are, afaik, not JAVA itself borking, but is the java based Jenkins slave/agent complaining loudly that the tests it was running died horribly - just FYI :-)

**Comment by ganeshmaharaj** [comment]
should we re-kick the CI or is this PR good to merge?

**Comment by chavafg** [comment]
centos job was renamed, and the new job passed. power8 we know that is not ready... we can merge this one.

**Comment by jodh-intel** [comment]
Too late! ;)

**Pull request merged**
