### PR TITLE
tracing: Add opentracing support

### LINKED ISSUE #123: Add opentracing support.
See: https://github.com/kata-containers/kata-containers/issues/27.

### PR DESCRIPTION
**Pull request by jodh-intel**
Added a new `-trace` CLI option which, if specified, enables opentracing
support using Jaeger.

Fixes #123.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Which reminds me of the [limerick in the C++ specification document](https://www.reddit.com/r/ProgrammerHumor/comments/31ckx0/the_c_standard_has_a_limerick_in_it/) :-)

**Comment by jodh-intel** [comment]
:smile:

**Comment by jodh-intel** [comment]
Blocked on #125.

**Comment by jodh-intel** [comment]
Blocked on #127...

**Comment by sboeuf** [comment]
@jodh-intel just merged #127, this PR is unblocked now ;)

**Comment by jodh-intel** [comment]
@sboeuf - ha - I just read your comment and though, "I don't remember merging that PR" then realised what you mean ;)

/me will update after the meeting...

**Comment by jodh-intel** [comment]
Branch updated.

The traces aren't quite as exciting as the runtime or agent ones, but here it is... ;)

**Comment by jodh-intel** [comment]
Oops - tests need tweaking...

**Comment by jodh-intel** [comment]
Whilst waiting for reviews, since I just about trust myself...

/test

**Comment by jodh-intel** [comment]
Ping @kata-containers/shim - please can you review! ;)

**Pull request merged**
