### PR TITLE
# Kata Containers 1.2.0

### PR DESCRIPTION
**Pull request by jcvenegas**
- Improve announcement msg
- CI: Update bash on Travis osx for hash support

8926d97 logging: Add more fields to initial announce message
7bf6add logging: Show announce string with initial message
392d63c CI: Update bash on Travis osx for hash support

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Comment by jcvenegas** [comment]
Ubuntu failed with a network issue in CI. 
```
not ok 1 Verify nginx connectivity between pods
# (from function `setup' in test file nginx.bats, line 20)
#   `sudo -E crictl pull "$busybox_image"' failed
# node "ubuntu-1604-277" untainted
# time="2018-08-07T17:08:34Z" level=fatal msg="pulling image failed: rpc error: code = Unknown desc = Error parsing image configuration: Get https://registry-1.docker.io/v2/library/busybox/blobs/sha256:e1ddd7948a1c31709a23cc5b7dfe96e55fc364f90e1cebcde0773a1b5a30dcda: EOF" 
# Error from server (NotFound): deployments.extensions "nginx-service" not found
# Error from server (NotFound): services "nginx-service" not found
# error: resource name may not be empty
# /tmp/jenkins/workspace/kata-containers-shim-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/integration/kubernetes/../../.ci/lib.sh: line 149: [: : integer expression expected
# No resources found.
```
Rebuild

**Comment by grahamwhaley** [comment]
travis fail is the OSX issue.
I'm not quite sure how a single digit change in a version number can get us a -1.74% coverage drop?? :-/

**Comment by grahamwhaley** [comment]
I can't see how that coverage fail can be right - so, I'm going to over-rule it and force merge...

**Pull request merged**
