### PR TITLE
github: Remove issue template and use central one

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the GitHub issue template from this repository. We already have a
central set of templates [1] that are being used so the template in this
repository is redundant.

[1] - https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/

Fixes: #270.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by devimc — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
Could someone from @kata-containers/documentation tal for that final ack... ;)

**Comment by jodh-intel** [comment]
Ping!!!

**Review by cmaf — APPROVED** [review]

**Pull request merged**
