### PR TITLE
vendor: Fix out of sync vendor issue

### PR DESCRIPTION
**Pull request by jodh-intel**
Fixed vendoring "out of sync" issue:

```sh
$ dep check
321github.com/gogo/protobuf: hash of vendored tree not equal to digest in Gopkg.lock
322google.golang.org/grpc: hash of vendored tree not equal to digest in Gopkg.lock
$ echo $?
1
```

The "safest" approach would seem to be to update the lock file to match
what we're building with in `vendor/*`, but that didn't work as
expected:

```
$ dep ensure -update -no-vendor
$ echo $?
0
$ dep check
github.com/codahale: unused project
github.com/creack/pty: missing from vendor
github.com/davecgh/go-spew: hash of vendored tree not equal to digest in Gopkg.lock
github.com/docker/docker: hash of vendored tree not equal to digest in Gopkg.lock
github.com/gogo/protobuf: hash of vendored tree not equal to digest in Gopkg.lock
github.com/golang/protobuf: hash of vendored tree not equal to digest in Gopkg.lock
github.com/konsorten/go-windows-terminal-sequences: missing from vendor
github.com/kr/pty: hash of vendored tree not equal to digest in Gopkg.lock
github.com/opentracing/opentracing-go: hash of vendored tree not equal to digest in Gopkg.lock
github.com/pkg/errors: hash of vendored tree not equal to digest in Gopkg.lock
github.com/sirupsen/logrus: hash of vendored tree not equal to digest in Gopkg.lock
github.com/stretchr/testify: hash of vendored tree not equal to digest in Gopkg.lock
github.com/uber/jaeger-client-go: hash of vendored tree not equal to digest in Gopkg.lock
github.com/uber/jaeger-lib: hash of vendored tree not equal to digest in Gopkg.lock
golang.org/x/crypto: unused project
golang.org/x/sys: hash of vendored tree not equal to digest in Gopkg.lock
golang.org/x/text: hash of vendored tree not equal to digest in Gopkg.lock
google.golang.org/genproto: hash of vendored tree not equal to digest in Gopkg.lock
google.golang.org/grpc: hash of vendored tree not equal to digest in Gopkg.lock
gopkg.in/yaml.v2: missing from vendor
$ echo $?
1
```

Therefore, I took the other approach and updated the `vendor/*` tree based
on the lockfile:

```
$ dep ensure -v -update google.golang.org/grpc
Root project is "github.com/kata-containers/shim"
 1 transitively valid internal packages
 15 external packages imported from 10 projects
(0)   ✓ select (root)
(1)     ? attempt github.com/kata-containers/agent with 3 pkgs; at least 1 versions to try
(1)         try github.com/kata-containers/agent@0ff30063f7e71eb0f48d60c21156cd18b8a58024
(1)     ✓ select github.com/kata-containers/agent@0ff30063f7e71eb0f48d60c21156cd18b8a58024 w/4 pkgs
(2)     ? attempt github.com/gogo/protobuf with 3 pkgs; at least 1 versions to try
(2)         try github.com/gogo/protobuf@342cbe0a04158f6dcb03ca0079991a51a4248c02
(2)     ✓ select github.com/gogo/protobuf@342cbe0a04158f6dcb03ca0079991a51a4248c02 w/5 pkgs
(3)     ? attempt github.com/kr/pty with 1 pkgs; at least 1 versions to try
(3)         try github.com/kr/pty@v1.1.0
(3)     ✓ select github.com/kr/pty@v1.1.0 w/1 pkgs
(4)     ? attempt github.com/grpc-ecosystem/grpc-opentracing with 1 pkgs; at least 1 versions to try
(4)         try github.com/grpc-ecosystem/grpc-opentracing@master
(4)     ✓ select github.com/grpc-ecosystem/grpc-opentracing@master w/1 pkgs
(5)     ? attempt github.com/opentracing/opentracing-go with 1 pkgs; at least 1 versions to try
(5)         try github.com/opentracing/opentracing-go@v1.0.2
(5)     ✓ select github.com/opentracing/opentracing-go@v1.0.2 w/2 pkgs
(6)     ? attempt github.com/moby/moby with 1 pkgs; at least 1 versions to try
(6)         try github.com/moby/moby@v1.13.1
(6)     ✓ select github.com/moby/moby@v1.13.1 w/1 pkgs
(7)     ? attempt github.com/Azure/go-ansiterm with 1 pkgs; at least 1 versions to try
(7)         try github.com/Azure/go-ansiterm@master
(7)     ✓ select github.com/Azure/go-ansiterm@master w/2 pkgs
(8)     ? attempt github.com/mdlayher/vsock with 1 pkgs; at least 1 versions to try
(8)         try github.com/mdlayher/vsock@738c88d6e4cfd60e8124a5344fa10d205fd828b9
(8)     ✓ select github.com/mdlayher/vsock@738c88d6e4cfd60e8124a5344fa10d205fd828b9 w/1 pkgs
(9)     ? attempt github.com/docker/docker with 1 pkgs; at least 1 versions to try
(9)         try github.com/docker/docker@master
(9)     ✓ select github.com/docker/docker@master w/1 pkgs
(10)  ? revisit github.com/Azure/go-ansiterm to add 1 pkgs
(10)    ✓ include 1 more pkgs from github.com/Azure/go-ansiterm@master
(10)  ? revisit github.com/opentracing/opentracing-go to add 2 pkgs
(11)    ✓ include 3 more pkgs from github.com/opentracing/opentracing-go@v1.0.2
(10)  ? attempt github.com/hashicorp/yamux with 1 pkgs; at least 1 versions to try
(12)      try github.com/hashicorp/yamux@cc6d2ea263b2471faabce371255777a365bf8306
(12)  ✓ select github.com/hashicorp/yamux@cc6d2ea263b2471faabce371255777a365bf8306 w/1 pkgs
(11)  ? attempt github.com/sirupsen/logrus with 2 pkgs; at least 1 versions to try
(13)      try github.com/sirupsen/logrus@v1.0.4
(13)  ✓ select github.com/sirupsen/logrus@v1.0.4 w/2 pkgs
(12)  ? attempt golang.org/x/crypto with 1 pkgs; at least 1 versions to try
(14)      try golang.org/x/crypto@master
(14)  ✓ select golang.org/x/crypto@master w/1 pkgs
(13)  ? attempt golang.org/x/net with 1 pkgs; at least 1 versions to try
(15)      try golang.org/x/net@a8b9294777976932365dabb6640cf1468d95c70f
(15)  ✓ select golang.org/x/net@a8b9294777976932365dabb6640cf1468d95c70f w/1 pkgs
(14)  ? attempt google.golang.org/grpc with 1 pkgs; 79 versions to try
(16)      try google.golang.org/grpc@d11072e7ca9811b1100b80ca0269ac831f06d024
(16)  ✓ select google.golang.org/grpc@d11072e7ca9811b1100b80ca0269ac831f06d024 w/1 pkgs
(15)  ? attempt golang.org/x/sys with 1 pkgs; at least 1 versions to try
(17)      try golang.org/x/sys@master
(17)  ✓ select golang.org/x/sys@master w/1 pkgs
(16)  ? attempt github.com/opencontainers/runtime-spec with 1 pkgs; at least 1 versions to try
(18)      try github.com/opencontainers/runtime-spec@5806c35637336642129d03657419829569abc5aa
(18)  ✓ select github.com/opencontainers/runtime-spec@5806c35637336642129d03657419829569abc5aa w/1 pkgs
(17)  ? attempt github.com/uber/jaeger-client-go with 1 pkgs; at least 1 versions to try
(19)      try github.com/uber/jaeger-client-go@v2.15.0
(19)  ✓ select github.com/uber/jaeger-client-go@v2.15.0 w/17 pkgs
(18)  ? attempt github.com/stretchr/testify with 1 pkgs; at least 1 versions to try
(20)      try github.com/stretchr/testify@v1.2.0
(20)  ✓ select github.com/stretchr/testify@v1.2.0 w/1 pkgs
(19)  ? revisit google.golang.org/grpc to add 3 pkgs
(21)    ✓ include 23 more pkgs from google.golang.org/grpc@d11072e7ca9811b1100b80ca0269ac831f06d024
(19)  ? revisit golang.org/x/net to add 3 pkgs
(22)    ✓ include 7 more pkgs from golang.org/x/net@a8b9294777976932365dabb6640cf1468d95c70f
(19)  ? attempt github.com/pkg/errors with 1 pkgs; at least 1 versions to try
(23)      try github.com/pkg/errors@v0.8.0
(23)  ✓ select github.com/pkg/errors@v0.8.0 w/1 pkgs
(20)  ? revisit golang.org/x/sys to add 1 pkgs
(24)    ✓ include 1 more pkgs from golang.org/x/sys@master
(20)  ? attempt github.com/davecgh/go-spew with 1 pkgs; at least 1 versions to try
(25)      try github.com/davecgh/go-spew@v1.1.0
(25)  ✓ select github.com/davecgh/go-spew@v1.1.0 w/1 pkgs
(21)  ? attempt github.com/pmezard/go-difflib with 1 pkgs; at least 1 versions to try
(26)      try github.com/pmezard/go-difflib@v1.0.0
(26)  ✓ select github.com/pmezard/go-difflib@v1.0.0 w/1 pkgs
(22)  ? attempt github.com/uber/jaeger-lib with 1 pkgs; at least 1 versions to try
(27)      try github.com/uber/jaeger-lib@v1.5.0
(27)  ✓ select github.com/uber/jaeger-lib@v1.5.0 w/1 pkgs
(23)  ? attempt github.com/codahale/hdrhistogram with 1 pkgs; at least 1 versions to try
(28)      try github.com/codahale/hdrhistogram@master
(28)  ✓ select github.com/codahale/hdrhistogram@master w/1 pkgs
(24)  ? attempt google.golang.org/genproto with 1 pkgs; at least 1 versions to try
(29)      try google.golang.org/genproto@master
(29)  ✓ select google.golang.org/genproto@master w/1 pkgs
(25)  ? attempt github.com/golang/protobuf with 1 pkgs; at least 1 versions to try
(30)      try github.com/golang/protobuf@master
(30)  ✓ select github.com/golang/protobuf@master w/2 pkgs
(26)  ? revisit github.com/golang/protobuf to add 2 pkgs
(31)    ✓ include 5 more pkgs from github.com/golang/protobuf@master
(26)  ? attempt golang.org/x/text with 3 pkgs; at least 1 versions to try
(32)      try golang.org/x/text@master
(32)  ✓ select golang.org/x/text@master w/14 pkgs
  ✓ found solution with 99 packages from 26 projects

Solver wall times by segment:
              b-gmal: 3.712129078s
         b-list-pkgs: 3.656050035s
     b-source-exists: 3.339422548s
    b-rev-present-in: 2.424763025s
     b-list-versions: 1.729689179s
  b-deduce-proj-root: 224.232799ms
             satisfy:  38.054026ms
         select-atom:  33.326506ms
            new-atom:   4.903017ms
         select-root:    230.035µs
            add-atom:    194.084µs
               other:    119.945µs

  TOTAL: 15.163114277s

(1/2) Wrote github.com/gogo/protobuf@342cbe0a04158f6dcb03ca0079991a51a4248c02: hash of vendored tree didn't match digest in Gopkg.lock
(2/2) Wrote google.golang.org/grpc@d11072e7ca9811b1100b80ca0269ac831f06d024: hash of vendored tree didn't match digest in Gopkg.lock
$ echo $?
0
```

This clearly "worked" but since the `dep` metadata was out of sync in
the first place, we don't know which commits we've pulled in from
upstream, although we can of course see the file changes.

Note that I also added a "NOP" change to `Gopkg.lock` (in the comment
header) since the CI static analysis script will fail PRs that modify
files below `vendor/*` without also updating `Gopkg.lock`.

Fixes: #203.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hmm. This is odd. Travis is still failing in the original way as shown on PR #202, although wfm locally...?!?

**Comment by sboeuf** [comment]
@jodh-intel 
I have had a quick look and I think you're missing the update of `github.com/gogo/protobuf`.
An easy to solve this is to proceed as follow:
```bash
dep ensure -update github.com/gogo/protobuf
dep ensure -update google.golang.org/grpc
```
With those commands, both vendored directory get updated and the `dep check` succeed.

**Comment by jodh-intel** [comment]
Thanks @sboeuf!

**Pull request merged**
