### PR TITLE
Stable 1.5.1 rc backports

### PR DESCRIPTION
**Pull request by egernst**
backports from master branch:
pullapprove: remove it 
ci: Add a CODEOWNERS file for github ack checks

### CODE REVIEW

**Comment by grahamwhaley** [comment]
ack on us needing proper descriptions and subject lines - for every commit/PR/merge in every branch. no exceptions.

btw, @GabyCT @chavafg - I'm guessing you know about the 18.04 odd java crashes already? It has bombed in the jenkins agent:

```
Stderr: 
Running command '/usr/bin/docker [docker ps -a -f name=oj4Cvp0OTBgCqTqongzeRmIZ5OtpqY --format {{.Status}}]'
[docker ps -a -f name=oj4Cvp0OTBgCqTqongzeRmIZ5OtpqY --format {{.Status}}]
Timeout: 60 seconds
Exit Code: 0
Stdout: 
Stderr: 
Running command '/bin/ps [ps -ef]'
FATAL: command execution failed
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
```

I wonder if it could be related to the version of java installed on the 18.04 machines? Just a guess.

**Comment by chavafg** [comment]
I wasn't aware of this issue. @GabyCT can you please check?

**Comment by chavafg** [comment]
@grahamwhaley it also happened on Fedora job... not sure if there was a network issue on the jenkins server last night that made the VMs unreachable.

**Comment by GabyCT** [comment]
@chavafg , I have not see that error before

**Pull request merged**
