### PR TITLE
travis: Fix static-checks and bumg go version

### PR DESCRIPTION
**Pull request by chavafg**
travis: Add variable needed to run static checks
travis: bump golang version to 1.10.x

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
WE need one more ack over here y'all...!

**Comment by grahamwhaley** [comment]
I've not been tracking our CI health... are we expecting things to be passing. 16.04 seems unhappy with a k8s test:
```
ok 1 Exceeding memory constraints
not ok 2 Running within memory constraints
# (from function `waitForProcess' in file ../../.ci/lib.sh, line 164,
#  in test file k8s-memory.bats, line 47)
```

Travis fail is just the 'poison Apple' issue (missing `yq`).

**Comment by jodh-intel** [comment]
@grahamwhaley - yep - https://github.com/kata-containers/tests/issues/558

**Comment by grahamwhaley** [comment]
/me goes to nudge on the apple thread then....
/me goes to nudge 16.04 rebuild to see if that was transient or not...

**Comment by chavafg** [comment]
ubuntu 16.04 job now it failed pulling an image...
```
# time="2018-08-30T11:27:14Z" level=fatal msg="pulling image failed: rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage025667011/1": read tcp 10.0.0.11:53518->104.18.123.25:443: read: connection reset by peer" 
```

restarted job again.

**Comment by caoruidong** [comment]
As yq on macOS is fixed, we can merge this.

**Pull request merged**
